Documentation:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/MultilineOperationIndentation:
  Enabled: false

Metrics/MethodLength:
  Max: 15

Metrics/ClassLength:
  Max: 125

Metrics/LineLength:
  Max: 100

Metrics/AbcSize:
  Max: 20
